apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: musefys6/api-gateway:0.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8085
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
          resources:
            requests:
              memory: "256Mi"
              cpu: "0.2"
            limits:
              memory: "1Gi"   # Increase memory limit to 1GB (adjust as per your requirements)
              cpu: "0.5"      # You can adjust the CPU limit as needed
      restartPolicy: Always

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: api-gateway-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-gateway
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70

---

apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  selector:
    app: gateway
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 8085
  type: LoadBalancer


