global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus-i'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'spring-actuator'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['145.93.45.15:8087']