global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'music-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.88.250:8087'] # Replace with the actual address and port of your microservice

  - job_name: 'user-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.88.250:8082'] # Replace with the actual address and port of another microservice

  - job_name: 'security-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.88.250:8083'] # Replace with the actual address and port of another microservice

#  - job_name: 'api-gateway'
#    metrics_path: '/actuator/prometheus'
#    scrape_interval: 5s
#    static_configs:
#      - targets: ['localhost:8085'] # Replace with the actual address and port of another microservice
