apiVersion: apps/v1
kind: Deployment
metadata:
  name: music-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: music-service
  template:
    metadata:
      labels:
        app: music-service
    spec:
      containers:
        - name: music-service
          image: musefys6/music-service:0.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8087
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
          resources:
            requests:
              memory: "256Mi"
              cpu: "0.2"
            limits:
              memory: "1Gi"   # Increase memory limit to 1GB (adjust as per your requirements)
              cpu: "0.5"      # You can adjust the CPU limit as needed
      restartPolicy: Always

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: music-service-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: music-service
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

---
apiVersion: v1
kind: Service
metadata:
  name: music-service
spec:
  selector:
    app: music-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8087
  type: ClusterIP
